FROM python:latest

RUN mkdir /automation

RUN apt-get update && apt-get -y install vim

COPY  ./ozkokapitest /automation/ozkokapitest
COPY ./setup.py /automation

WORKDIR /automation

RUN python3 setup.py install
